import { createHash } from "node:crypto"
import { mkdir, stat } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { TCH_AGENT_HOME_DIR } from "../config/index"

/** Docker image label：把 Dockerfile 的 sha256 存到镜像 label，便于增量构建。 */
export const DOCKERFILE_HASH_LABEL = "ai.tch-agent.dockerfile-sha256"

/** Solver 镜像的目标架构：固定 amd64 */
export const RUNTIME_IMAGE_ARCH = "amd64"

/** Runtime 资源目录：~/.tch-agent/runtime/ */
export const RUNTIME_DIR = resolve(TCH_AGENT_HOME_DIR, "runtime")

/** Runtime self 目录（存 solver binary）：~/.tch-agent/runtime/self/ */
export const RUNTIME_SELF_DIR = resolve(RUNTIME_DIR, "self")

/**
 * 计算 Dockerfile 内容的 sha256。
 * 用于增量构建：hash 没变就跳过 build。
 */
export function hashDockerfileContent(content: string): string {
    return createHash("sha256").update(content).digest("hex")
}

/** 路径是否存在（吞掉异常） */
export async function pathExists(path: string): Promise<boolean> {
    try {
        await stat(path)
        return true
    } catch {
        return false
    }
}

/**
 * 把 Dockerfile + 辅助脚本（统称"runtime assets"）同步到 ~/.tch-agent/runtime/。
 * 同步是幂等的——每次都覆盖一遍，保证是最新版本。
 */
export async function resolveDockerfilePath(onProgress?: (msg: string) => void): Promise<string> {
    const targetDockerfile = resolve(RUNTIME_DIR, "Dockerfile")
    await mkdir(dirname(targetDockerfile), { recursive: true })

    const dockerfileContent = getSolverDockerfileContent()
    await Bun.write(targetDockerfile, dockerfileContent)

    onProgress?.(`Synced runtime Dockerfile to ${RUNTIME_DIR}`)
    return targetDockerfile
}

/**
 * 返回 solver Dockerfile 的内容。
 *
 * 设计原则：
 *   1. 基础镜像小（debian-slim）
 *   2. 装通用基础工具（curl/git/python 等）+ 少量 pentest 工具
 *   3. 工作目录 /root/workspace（容器 cwd）
 */
export function getSolverDockerfileContent(): string {
    return `# tch-agent solver image
# Auto-generated by tch-agent - DO NOT EDIT MANUALLY

FROM debian:bookworm-slim

# 配置内网 apt 镜像（加速构建）
RUN rm -rf /etc/apt/sources.list.d/*
RUN cat >/etc/apt/sources.list <<EOF
deb http://10.100.3.3:8081/repository/debian-bookworm/ bookworm main contrib non-free non-free-firmware
deb http://10.100.3.3:8081/repository/debian-bookworm/ bookworm-updates main contrib non-free non-free-firmware
deb http://10.100.3.3:8081/repository/debian-bookworm-security/ bookworm-security main contrib non-free non-free-firmware
EOF

# 基础工具（这些都在 debian apt 源里，肯定能装上）
RUN apt-get update && apt-get install -y --no-install-recommends \\
    ca-certificates \\
    curl \\
    wget \\
    git \\
    unzip \\
    vim \\
    nano \\
    python3 \\
    python3-pip \\
    python3-venv \\
    jq \\
    dnsutils \\
    iputils-ping \\
    netcat-openbsd \\
    tcpdump \\
    procps \\
    file \\
    less \\
    && rm -rf /var/lib/apt/lists/*

# 配置内网 pip 镜像（加速构建）
RUN pip3 config set global.index-url http://192.168.5.44:8081/repository/pip/simple/ && \\
    pip3 config set global.trusted-host 192.168.5.44

# 通过 pip 装 pentest 工具（pip 包都是源码或 wheel，不依赖系统包）
RUN pip3 install --no-cache-dir --break-system-packages \\
    requests \\
    beautifulsoup4 \\
    pwntools \\
    cryptography

# 工作目录
WORKDIR /root/workspace

# 默认命令（会被 docker run 的 cmd 覆盖）
CMD ["/bin/bash"]
`
}
