import { createHash } from "node:crypto"
import { mkdir, stat } from "node:fs/promises"
import { basename, dirname, resolve } from "node:path"
import { TCH_AGENT_HOME_DIR } from "../config/index"

/** Docker image label：把 Dockerfile 的 sha256 存到镜像 label，便于增量构建。 */
export const DOCKERFILE_HASH_LABEL = "ai.tch-agent.dockerfile-sha256"

/** Solver 镜像的目标架构：固定 amd64 */
export const RUNTIME_IMAGE_ARCH = "amd64"

/** Runtime 资源目录：~/.tch-agent/runtime/ */
export const RUNTIME_DIR = resolve(TCH_AGENT_HOME_DIR, "runtime")

/** Runtime self 目录（存 solver binary）：~/.tch-agent/runtime/self/ */
export const RUNTIME_SELF_DIR = resolve(RUNTIME_DIR, "self")

/**
 * 计算 Dockerfile 内容的 sha256。
 * 用于增量构建：hash 没变就跳过 build。
 */
export function hashDockerfileContent(content: string): string {
    return createHash("sha256").update(content).digest("hex")
}

/** 路径是否存在（吞掉异常） */
export async function pathExists(path: string): Promise<boolean> {
    try {
        await stat(path)
        return true
    } catch {
        return false
    }
}

/**
 * 把 Dockerfile + 辅助脚本（统称"runtime assets"）同步到 ~/.tch-agent/runtime/。
 * 同步是幂等的——每次都覆盖一遍，保证是最新版本。
 */
export async function resolveDockerfilePath(onProgress?: (msg: string) => void): Promise<string> {
    const targetDockerfile = resolve(RUNTIME_DIR, "Dockerfile")
    await mkdir(dirname(targetDockerfile), { recursive: true })

    const dockerfileContent = getSolverDockerfileContent()
    await Bun.write(targetDockerfile, dockerfileContent)

    onProgress?.(`Synced runtime Dockerfile to ${RUNTIME_DIR}`)
    return targetDockerfile
}

/**
 * 返回 solver Dockerfile 的内容。
 *
 * 设计原则：
 *   1. 基础镜像小（debian-slim）
 *   2. 装通用基础工具（curl/git/python 等）+ 少量 pentest 工具
 *   3. 工作目录 /root/workspace（容器 cwd）
 */
export function getSolverDockerfileContent(): string {
    return `# tch-agent solver image
# Auto-generated by tch-agent - DO NOT EDIT MANUALLY

FROM debian:bookworm-slim

# 配置内网 apt 镜像（加速构建）
RUN rm -rf /etc/apt/sources.list.d/*
RUN cat >/etc/apt/sources.list <<EOF
deb http://10.100.3.3:8081/repository/debian-bookworm/ bookworm main contrib non-free non-free-firmware
deb http://10.100.3.3:8081/repository/debian-bookworm/ bookworm-updates main contrib non-free non-free-firmware
deb http://10.100.3.3:8081/repository/debian-bookworm-security/ bookworm-security main contrib non-free non-free-firmware
EOF

# 基础工具（这些都在 debian apt 源里，肯定能装上）
RUN apt-get update && apt-get install -y --no-install-recommends \\
    ca-certificates \\
    curl \\
    wget \\
    git \\
    unzip \\
    vim \\
    nano \\
    python3 \\
    python3-pip \\
    python3-venv \\
    jq \\
    dnsutils \\
    iputils-ping \\
    netcat-openbsd \\
    tcpdump \\
    procps \\
    file \\
    less \\
    && rm -rf /var/lib/apt/lists/*

# 配置内网 pip 镜像（加速构建）
RUN pip3 config set global.index-url http://192.168.5.44:8081/repository/pip/simple/ && \\
    pip3 config set global.trusted-host 192.168.5.44

# 通过 pip 装 pentest 工具（pip 包都是源码或 wheel，不依赖系统包）
RUN pip3 install --no-cache-dir --break-system-packages \\
    requests \\
    beautifulsoup4 \\
    pwntools \\
    cryptography

# 工作目录
WORKDIR /root/workspace

# 默认命令（会被 docker run 的 cmd 覆盖）
CMD ["/bin/bash"]
`
}

/** 当前进程是否跑在 Bun runtime 下 */
function isBunRuntime(): boolean {
    const execName = basename(process.execPath).toLowerCase()
    return execName === "bun" || execName === "bun.exe"
}

/**
 * 容器内 package.json 的占位内容。
 * Bun 需要它把 cwd 当成包根。
 */
const GENERATED_RUNTIME_PACKAGE_JSON = {
    name: "tch-agent-runtime",
    version: "0.0.1",
    private: true,
    type: "module",
}

/**
 * 【dev 模式】用 Bun 现场编译一份 linux-x64 solver binary。
 *
 * 让本地改代码后，下次启动 solver 自动用最新版本。
 */
export async function ensureSolverBinary(): Promise<string> {
    const binDir = RUNTIME_SELF_DIR
    const binPath = resolve(binDir, "tch-agent-linux-x64")

    const projectRoot = resolve(import.meta.dir, "../../../..")
    const buildScript = resolve(projectRoot, "scripts/build.ts")

    await mkdir(binDir, { recursive: true })

    console.log(`[build] compiling solver binary to ${binPath}...`)
    const proc = Bun.spawn(
        ["bun", buildScript, "bun-linux-x64-baseline", binPath],
        {
            cwd: projectRoot,
            stdout: "inherit",
            stderr: "inherit",
        },
    )
    const exitCode = await proc.exited
    if (exitCode !== 0) {
        throw new Error(`Failed to compile solver binary (exit ${exitCode})`)
    }

    await Bun.write(
        resolve(binDir, "package.json"),
        JSON.stringify(GENERATED_RUNTIME_PACKAGE_JSON, null, 2),
    )

    return binPath
}

/**
 * 确保 ~/.tch-agent/runtime/self/package.json 存在。
 * 容器内 Bun 需要它把 cwd 识别为包根。
 */
async function ensureRuntimePackageManifest(): Promise<string> {
    const binDir = RUNTIME_SELF_DIR
    const path = resolve(binDir, "package.json")
    await mkdir(binDir, { recursive: true })
    await Bun.write(path, JSON.stringify(GENERATED_RUNTIME_PACKAGE_JSON, null, 2))
    return path
}

/**
 * 决定容器内用什么 binary 跑 solver，返回挂载和启动命令。
 *
 * 三种来源（按优先级）：
 *   1. Bun runtime (dev) → 现场编译 linux-x64 binary
 *   2. Linux x64 宿主 → 复用宿主 binary
 *   3. 其他平台 → 嵌入式 binary（本课时简化为 throw）
 *
 * @returns { binds, cmd }
 *   - binds: docker -v 参数
 *   - cmd: 容器启动命令
 */
export async function resolveSolverInjection(): Promise<{
    binds: string[]
    cmd: string[]
}> {
    let binary: string
    const packageJson = await ensureRuntimePackageManifest()

    if (isBunRuntime()) {
        binary = await ensureSolverBinary()
    } else if (process.platform === "linux" && process.arch === "x64") {
        binary = process.execPath
    } else {
        throw new Error(
            `Unsupported platform: ${process.platform}/${process.arch}. Run under Bun instead.`,
        )
    }

    return {
        binds: [
            `${binary}:/opt/tch-agent/tch-agent:ro`,
            `${packageJson}:/opt/tch-agent/package.json:ro`,
        ],
        cmd: ["/opt/tch-agent/tch-agent", "solver", "rpc"],
    }
}
